---
title: "Response Time"
output: html_notebook
---


# DIFFUSION w varying drift
```{r}

#diffusion model 
nreps <- 1000
nsamples <- 5000

dt <-     0.001
s <-      0.1

a <-      0.1       # Threshhold

ndt <-    300       # Non Decision Time
ndt_var <- 0        # NDT Variance

drift <-  0.15      # Drift rate
drift_var <- 0      # Drift Variance

switch <- 500
values = matrix(runif(20, -1,1), ncol=2, nrow=10)

# one value, many trials
trial_drift = values[,1] * drift + rnorm(length(values[,1]),0,drift_var)

nsamples = 10

cumsum(c(0, rnorm(nsamples*length(trial_drift),trial_drift*dt,sqrt(dt)*s)))

# example
M <- matrix(1:6, nrow=3, byrow=TRUE)
M
t(apply(M, 1, cumsum))
# add leading row of zeros

latencies <- rep(0,nreps) 
responses <- rep(0,nreps)
evidence <- matrix(0, nreps, nsamples+1) # +1 to account for the starting value

for (i in c(1:nreps)) { 
  # Trial updating
  # Starting Point
  ndt = ndt + ndt_var
  
  # Drifts
  trial_drift.1 = values[,1] * drift + rnorm(length(values[,1]),0,drift_var)
  trial_drift.2 = values[,2] * drift + rnorm(length(values[,1]),0,drift_var)
  
  # Evidence Accumulation  
  evidence[i,] <- cumsum(c(0,
                           rnorm(switch,drift[1]*dt,sqrt(dt)*s),
                           rnorm(nsamples-switch,drift[2]*dt,sqrt(dt)*s)))
  
  p <-  which(abs(evidence[i,])>a)[1]
  responses[i] <- sign(evidence[i,p])
  latencies[i]  <- p
}
latencies <- latencies + non_decision

layout(m=array(1:2,dim=c(1,2)))
hist(latencies[responses==1])
hist(latencies[responses==-1])


```

```{r}
# Function to calculate the threshold crossing time 
# PDF for one node (node #1). Arguments are as for
# fptcdf above.
fptpdf=function(t,A,b,v,sdv) {
  zs=t*sdv ; zu=t*v ; chiminuszu=b-zu
  chizu=chiminuszu/zs ; chizumax=(chiminuszu-A)/zs
  (v*(pnorm(chizu)-pnorm(chizumax)) + 
    sdv*(dnorm(chizumax)-dnorm(chizu)))/A
}
```


```{r}
# playing with rnorm
a = c(0, 10, 100)
evidence = rnorm(rnorm(evidence, mean=evidence, sd=1))
```



# CDF of data
# Violin plot

[.005,.1], .3, .5, .7, .9, ]